application:
  host: 127.0.0.1
  port: 8000
  telemetry:
    kind: Stdout
    log_level: DEBUG
  tx:
    vk: tests/data/params/transfer_verification_key.json
    params: tests/data/params/transfer_params.bin
    client_mock_key: 6cbed15c793ce57650b9877cf6fa156fbef513c4e6134f022a85b1ffdd59b2a1
  tree:
    params: tests/data/params/tree_params.bin
web3:
  relayer_fee: 0
  provider_endpoint: http://localhost:8545
  abi_path: ../configuration/pool-abi.json
  pool_address: c89ce4735882c9f0f0fe26686c53074e09b0d550
  gas_limit: 2000000
  scheduler_interval_sec: 5
  credentials:
      secret_key: 6370fd033278c143179d81c5526140625662b8daa446c22ee2d73db3707e620c
