application:
  host: 127.0.0.1
  port: 8000
  db_path: none
  telemetry:
    kind: Stdout
    log_level: DEBUG
  tx:
    vk: tests/data/params/transfer_verification_key.json
    params: tests/data/params/transfer_params.bin
    client_mock_key: cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe
  tree:
    params: tests/data/params/tree_params.bin
web3:
  relayer_fee: 0
  provider_endpoint: http://localhost:8545
  provider_timeout_sec: 180
  abi_path: ./configuration/pool-abi.json
  pool_address: cafecafecafecafecafecafecafecafecafecafe
  gas_limit: 2000000
  scheduler_interval_sec: 5
  trm_endpoint: http://localhost:8081/wallet_screening
  start_block: 0
  rollback_step: 5
  batch_size: 3000
  credentials:
      secret_key: cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe
      trm_api_key: api_key  
trm:
  host: http://127.0.0.1
  port: 8084
  path: /trm_mock
  api_key: api_key
