application:
  host: 127.0.0.1
  port: 8000
  tx:
    vk: tests/data/params/tx_vk.json
  tree:
    params: ./data/params
web3:
  provider_endpoint: http://localhost:8545
  pool_address: 0x
  abi_path: /Users/vladimirpopov/Blockchain/zkbob/relayer-rs/configuration/pool-abi.json
  credentials:
    secret_key: 0x...
