name: Docker Image CI

on:
  push:
    branches: [ "custody_image" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ghcr.io/zkBob/zkbob-cloud

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PHASE2_BN256_SSH_KEY }}
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - uses: Swatinem/rust-cache@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build relayer-rs
      run: cargo build --release && cp ./target/release/relayer-rs ./docker

    - name: Download bunyan
      run: cargo install bunyan && cp $(which bunyan) ./docker

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./docker
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}